name: pull-request-workflow 1
on:
  pull_request:
    types: [opened]

jobs:
  pull-request-job:
    runs-on: ubuntu-latest
    steps:
    - name: steps1
      run: echo hello world
    - name: steps2
      run: |
        echo hello world
        echo github action