name: push-workflow 2
on: push

jobs:
  push-job:
    runs-on: ubuntu-latest
    steps:
    - name: steps1
      run: echo hello world
    - name: steps2
      run: |
        echo hello world
        echo github action