name: cicd-iam-test
on: push

jobs:
  image-build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Configure AWS Credentials
      id: credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ap-northeast-2
        role-to-assume: arn:aws:iam::045510281556:role/githib-actions